# Generated by Django 5.2.8 on 2025-12-14 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{10,15}$', 'Введите корректный номер телефона')]),
        ),
    ]
