# Generated by Django 5.2.8 on 2025-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carscharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cars', models.ManyToManyField(to='cars.car')),
            ],
        ),
    ]
