# Generated by Django 5.2.8 on 2025-11-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarsCategory',
        ),
    ]
