# Generated by Django 5.2.8 on 2025-11-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carscategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carscategories',
            old_name='car_ip',
            new_name='car_id',
        ),
    ]
