# Generated by Django 5.2.8 on 2025-11-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carcategory_car_category_delete_carscategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carscharacteristics',
            options={'verbose_name': ('Характеристика авто',), 'verbose_name_plural': 'Характеристики авто'},
        ),
        migrations.RemoveField(
            model_name='carscharacteristics',
            name='car_id',
        ),
        migrations.AddField(
            model_name='carscharacteristics',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='cars.car'),
        ),
    ]
