# Generated by Django 5.2.8 on 2025-11-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carscharacteristics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carscharacteristics',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='cars.car'),
        ),
    ]
