# Generated by Django 5.2.8 on 2025-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_options_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
    ]
