# Generated by Django 5.2.8 on 2025-12-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0011_alter_car_car_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('SBP', 'SBP')], default='Card')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive'), ('APPROVED', 'Approved')], default='New')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
